"""empty message

Revision ID: 1ebce8eb31a8
Revises: f898085e78ba
Create Date: 2022-10-19 15:47:16.161391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ebce8eb31a8'
down_revision = 'f898085e78ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transacao', sa.Column('conta_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transacao', 'conta', ['conta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transacao', type_='foreignkey')
    op.drop_column('transacao', 'conta_id')
    # ### end Alembic commands ###
